
-- Generated by ORDS REST Data Services 21.4.3.r1300919
-- Schema: IOT  Date: Mar Jun 07 03:09:11 2022 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'IOT',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'iot',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'vocs',
      p_base_path      => '/vocs/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vocs',
      p_pattern        => 'getMsg/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vocs',
      p_pattern        => 'getMsg/',
      p_method         => 'GET',
      p_source_type    => 'json/query;type=single',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from vocs  where id = 28');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'vocs',
      p_pattern        => 'insertVoc/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vocs',
      p_pattern        => 'insertVoc/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select * from vocs');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'vocs',
      p_pattern        => 'insertVoc/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'declare 
    l_voc_id number;
begin
    for c in (
        select
                device_id,
                device_name,
                humidity,
                temperature,
                toluene
        from json_table ( :body,  ''$[*]'' 
            columns
                device_id        varchar2(4000),
                device_name      varchar2(4000),
                humidity         number(5,2),
                temperature      number(5,2),
                toluene          number(9,2)
        )
    ) loop
        l_voc_id := vocs_seq.nextval;

        insert into vocs (
            id,
            device_id,
            device_name,
            humidity,
            temperature,
            toluene,
            created
        )
        values (
            l_voc_id,
            c.device_id, 
            c.device_name,
            c.humidity,
            c.temperature,
            c.toluene,
            systimestamp
        );

    end lo' || 'op;
    
end;');

    
        
COMMIT;

END;